### PR TITLE
⚡️ Tuning

### PR DESCRIPTION
**Pull request by chaoticthegreat**
Closes RCD-41, RCD-42

### CODE REVIEW

**Comment by realjoshuau** [comment]
Is this draft

**Comment by ThatXliner** [comment]
No, we tuned these values today

**Comment by realjoshuau** [comment]
Are you guys still tuned?

**Comment by ThatXliner** [comment]
> Are you guys still tuning?

As of my last comment, mechanical was doing some changes on the robot + charging DS

**Comment by chaoticthegreat** [comment]
Since this is just constants im merging it

**Comment by realjoshuau** [comment]
👍

**Pull request merged**
