### PR TITLE
Refactor Feature Flags

### PR DESCRIPTION
**Pull request by chaoticthegreat**
Closes RCD-30

### CODE REVIEW

**Comment by ThatXliner** [comment]
I was thinking more of like a dummy class that implements the IO interface for every IO interface

**Comment by chaoticthegreat** [comment]
less code = better?

**Review by realjoshuau — APPROVED** [review]
lgtm

**Comment by ThatXliner** [comment]
Does your current code handle logging?

**Comment by chaoticthegreat** [comment]
Logging what?

**Comment by ThatXliner** [comment]
Ig it doesn't matter as long as nothing gets executed.

What I was worried about was that the logging code would call methods on TalonFX objects even when disabled

**Comment by realjoshuau** [comment]
The TalonFX/MonitoredTalonFX objects should still exist, the disabled flag just no-ops all the Command functions.

**Pull request merged**
